### ISSUE TITLE
Unable to connect to database on render. Also I want to ask some silly questions 

### ISSUE THREAD

**Issue by bhaveshhptl** [PritK99/Legal-Documentation-Assistant#10]
Hi Sir/Ma'am, 
I created my DB on render in Singapore region. But while connecting it showed this following  error.
![Screenshot 2024-09-26 124035](https://github.com/user-attachments/assets/962df16e-1d50-48bc-a92c-993c63393bc7)
Also where should my .env file be located according to file architecture ? Under server or under root directory?
I also ran frontend and it shows loading.... Is it because backend has not been executed yet?
![Screenshot 2024-09-26 at 13-26-15 DocBuddy](https://github.com/user-attachments/assets/d3464338-1e10-4d8a-b0a8-ee864513b1d2)

**Comment by PritK99** [comment]
Hey,
1) The error suggests there might be issue with the credentials. Just ensure that all the credentials are correct and you haven't modified any other code. Also make sure you follow the steps in `./README` properly.
2) The `.env` file should be in server directory.
3) Yes, you will see the frontend load up categories once the backend starts.

Please share the exact steps followed if the issue continue to persist.

**Comment by bhaveshhptl** [comment]
Hi sir,
 Thanks for the reply .I didn't change the code and the credentials I have verified. I have a confusion while giving the name of the DB , there are 2 names , 1 which I had to give and 1 which the render website generated. I put the latter in .env file.
 
![Screenshot 2024-09-26 150250](https://github.com/user-attachments/assets/b1b2e7e6-8228-4eba-837b-5ff20ea56c9a)
![Screenshot 2024-09-26 150111](https://github.com/user-attachments/assets/bb808ff2-6d5a-44f7-b2d2-1f2374bcc63e)

I will again retry cloning locally and update you later.

**Comment by bhaveshhptl** [comment]
After retrying cloning locally , The issue still persists. 
Here's the timeline.
Yesterday , I followed the exact steps in Readme File and created the DB and it was created successfully. But when I ran backend , I ran into some issues.
Today morning , I tried following same steps but the error which was not there yesterday, started appearing today. And it has been the case for the whole day now .

**Comment by PritK99** [comment]
Could you provide a description for the error?

**Comment by bhaveshhptl** [comment]
I figured it out and the code ran successfully, turns out the DB was already created I suppose. But I deleted my old DB and created a new one and this time the code ran successfully.. I am not much experienced with web development so had silly doubts 😅.
Sorry for the mess @PritK99.
