### ISSUE TITLE
how to establish the connection with the database in render..I get a issue while creating the database

### ISSUE THREAD

**Issue by AnushaPraba** [PritK99/Legal-Documentation-Assistant#7]
(docbuddy) PS C:\Users\anush\Legal-Documentation-Assistant\server> python createdatabase.py
Traceback (most recent call last):
  File "C:\Users\anush\Legal-Documentation-Assistant\server\createdatabase.py", line 10, in <module>
    conn = psycopg2.connect(database='final_legal_documentation', user='final_legal_documentation_user',
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anush\Legal-Documentation-Assistant\server\docbuddy\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "dpg-ckah8tcg66mc73falae0-a.oregon-postgres.render.com" (35.227.164.209), port 5432 failed: SSL connection has been closed unexpectedly
I get this error while creating the database.so can u give me suggestions of what to do to resolve this error?

**Comment by vrnimje** [comment]
Please pull the latest version of this repository locally. It seems that you are executing a previous version of the `createdatabase.py` file. 
Let us know if the issue persists

**Comment by bhaveshhptl** [comment]
Hi , I am also facing the same issue. How to resolve this? 
![Screenshot 2024-09-26 123954](https://github.com/user-attachments/assets/c1df1a2d-f58a-4c5b-9ac8-0952e557929a)
![Screenshot 2024-09-26 124336](https://github.com/user-attachments/assets/82ce268a-59b8-486d-9551-31959b36ae1c)

**Comment by AnushaPraba** [comment]
I encountered this error because the database with all the information is
already created.
So when I again run the "create database command" it gave me error.
To rectify this,we can run the next command..i.e.,"python app.py"
directly without running the create database command
I got the code work in my system this way.Try this.

**Comment by bhaveshhptl** [comment]
I see , I tried that and while I ran through "python app.py" it is also giving me error #8 . Also after fixing #8 was the code running completely, or you were facing errors in backend?
